### ISSUE TITLE
Process died with <Signals.SIGABRT: 6>

### ISSUE THREAD

**Issue by mdka00001** [uds-helms/PROPORES#14]
Dear Markus-Hollander

I am facing an issue while running a batch process for 3500 proteins. For some of the proteins, the process terminates with the error message "Process died with <Signals.SIGABRT: 6>". 

But if I process the proteins individually in web version, I get the outputs for all pore-id, axis-trace and gate-open query.

Could you please tell me what might be the reason?

My Worksystem is Core i9 3.3 Ghz 36 cores. Ram: 128 GB.

**Comment by Markus-Hollander** [comment]
Hello!

I’m sorry that you ran into issues with the batch processing. We have not encountered this particular error before, so I will have to do a bit more digging into the possible causes and hopefully fixes.

Based on the error message I assume that you are running it on a UNIX-based OS, could you please let me know which OS exactly?

Could you also list which parameters you are using for the batch processing, and which parameters were selected in the web version?

If possible, you could also give me one of the proteins that is not working in the batch processing but on the web server? It should be possible to attach the file here in the issue tracker.

Kind regards

**Comment by mdka00001** [comment]
Dear Markus
I am running all the process in Ubuntu 18.04.3 LTS system.

I ran a pore-id process for all 3500 proteins as a single process. Around 152 proteins failed to generate axis-trace and gate-open input data. Later I run the remaining 152 proteins in a separate process. Here, some proteins generated axis-trace and gate-open input data. 

So, I selected one of the proteins that failed to generate data and uploaded in the webserver. Unfortunately, the webserver kept running the process without generating any output. I used default parameters for the analysis both in webserver and stand alone process.

As far I understood from the error code, the process gets terminated for some reason.

Here I have uploaded the protein pdb file.
[AF-A8CG34-F1-model_v4.zip](https://github.com/uds-helms/ProPores2/files/10579354/AF-A8CG34-F1-model_v4.zip)

**Comment by Livia-Rasp** [comment]
Sorry to interfere here, but out of curiosity I have taken a look at how the provided protein does look like in a PDB viewer. And this is the result with surface representation:

<img width="476" alt="Screenshot 2023-02-03 192829" src="https://user-images.githubusercontent.com/3390392/216679720-45ddd8c3-0d4c-4dc9-813d-254d3a5e70a2.png">

This is a rather odd structure, when it comes to the surface, which I imagine could lead to unexpected behavior of ProPores.
If I had to guess what it is, I would say it's a denatured protein without tertiary structure.

**Comment by Markus-Hollander** [comment]
Hello!

Thank you for looking at the structure. It does look a bit odd. I’ll keep that in mind as a potential issue for ProPores.
I am currently limited to my laptop and only a portion of my ProPores development files since I am still on vacation (for the next week). However, I have started running the file you provided. Since it is a larger protein, it will take a while to either finish or abort. 

In the meantime, could you also attach a ZIP of the files that were generated for your run of “AF-A8CG34-F1-model_v4.pdb”. That way I can use the information generated up to the point of aborting the run to see where in the process it stopped and potentially why.

Additionally, would it be possible to run the propores_status.py script for your batch processing directory of the 3500 proteins, and then also for the 150 proteins that did not work? With that, I can get a much better overview of the sizes, pores etc. of the proteins where it worked and for those that did not.

For clarification: Your first post mentioned that there were there also proteins that did not work when you ran it on your machine but did work on the webserver (as in, all the files were generated) but in the second post it sounds more like they did not finish after all on the webserver? If you have a protein that did not work for you but did completely finish on the webserver, could you also attach that protein and the files that were generated for it?

Kind regards

**Comment by Markus-Hollander** [comment]
Hello! 

The provided protein has 8822 atoms, which means it is on the larger side. With the default parameters that means that ProPores will automatically switch into the standalone mode to preserve RAM. In that mode, the runtime primarily depends both on the number of unique atom pairs and whether the protein structure makes it easy to discard a lot of them right away as unsuitable. 

Due to the size of this protein and its unusual structure, this seems to take quite a long (my laptop is still working on it). The long runtime would also explain why you did not see the webservice returning a result. Since some of the proteins did not work in the large batch but did work in the smaller batch, it may be possible that the abortion is not caused by ProPores itself but by the multiprocessing workers in the batch script that eventually run against some limitations set by the OS and thus stops that the scheduled jobs that take too long.

Today, I ran the given protein in ray-trace mode (`--mode 1`) and it did finish without problems within a few minutes. Due to the quite limited RAM on my laptop, I had to reduce the resolution (as in, increase the value of the `-b` parameter). I used a resolution of 3.0Å. which is also the default resolution used by the webservice. The default resolution used by ProPores itself, and thus by the batch script is 1.0Å.

Since you have 128 GB RAM available, you should be able to run the ray-trace mode with the default 1.0Å even for the larger proteins, to stay consistent with the results for the rest of the proteins. You can do this with the batch script by adding

`-- args --mode 1`

**at the end** of your command, which will pass `--mode 1` to ProPores and thus manually tell it to use ray-tracing. Because I do not know how much larger the other proteins are that you still need to process or how many other processes are run on your system, it may be best if you limit `--cores` to 1 or 2 to be on the safe side (**before** `--args ....`), and maybe also try it only on a few of the problem proteins at first.

Please let me know if using the ray-trace mode works for you. It would still be good if you could also provide the information and batch status that I inquired about in my previous post.

Have a nice weekend!

**Comment by mdka00001** [comment]
Dear Markus
Thanks a lot for taking time and having a look at the issue. 

To run the process on the large dataset, I assigned `-- cores` to 36. Because my processor has 36 cores, and I thought assigning all the cores might do the computation faster. However, to complete all 3500 proteins, it took almost two weeks. 

Do you think using the `ray-trace` mode to 1.0A and assigning cores to 2 will do the process faster?

Also, since I need to run `axis-trace` for all the process, does the batch-process script of python allow to run axis_trace in batch similar to pore-id? or do I need to restart the process from beginning and do pore-id and axis-trace simultaneously?

**Comment by Markus-Hollander** [comment]
Hello!

> Because my processor has 36 cores, and I thought assigning all the cores might do the computation faster.

It's generally not good to assign all available cores.

> Do you think using the ray-trace mode to 1.0A and assigning cores to 2 will do the process faster?

The 1.0Å is necessary because that is the resolution of all your other runs, so if you want to compare the remaining 150 to the others, they should have the same resolution. With ray-trace, the issue is RAM, hence the limitation on simultaneous processes.

To be clear, you do not need to run all 3500 again. This is specifically for those ~150 that were not completed, and as I mentioned, it's best if you try it on a few of them first to see whether it works in ray-trace mode to begin with. If it works, then we know that we correctly identified the issue and you have an idea for how long each run will take on your machine.

> Also, since I need to run axis-trace for all the process, does the batch-process script of python allow to run axis_trace in batch similar to pore-id? or do I need to restart the process from beginning and do pore-id and axis-trace simultaneously?

If you have not enabled axis-trace in your run, it should generate the required input files automatically for a later run (unless you explicitly disabled that). You can confirm this by going to the **results** folder of your batch and from there into the subdirectory of a particular protein. If there is a directory called "axis_trace_input", then you do not need to run pore-id again.

![image](https://user-images.githubusercontent.com/7683033/217025676-369e86b0-47cf-43f5-afc0-c714ec00814e.png)

I have adjusted the batch script for you:

[propores_batch.zip](https://github.com/uds-helms/ProPores2/files/10664995/propores_batch.zip)

For the batch where you have already run Pore ID, you can run axis trace by using the normal batch command (input directory with all the PDB files that you used for the first run of the batch, the results directory from the first batch, the path to the ProPores executable). All you need to change is the argument behind `--args` from `pore-id` to `axis-trace`. As long `axis-trace` is specified without `pore-id`, the batch script will then automatically find the default axis-trace input directory for each protein in your batch and pass that to ProPores to compute the axes. 

**For example:**
Input directory:
![image](https://user-images.githubusercontent.com/7683033/217028730-cce4c469-93c3-413c-85ce-da8c457d19a9.png)

Results directory from the previous run:
![image](https://user-images.githubusercontent.com/7683033/217028839-bfc60224-8877-4bbc-939a-2814ca635676.png)

Corresponding batch script call:
![image](https://user-images.githubusercontent.com/7683033/217029105-2625e226-b047-4e69-b9fb-a0a0c162ee9d.png)

**Also, please provide the information I asked about.**

**Comment by mdka00001** [comment]
Dear Markus,

Thank you for the reply. 

Here are the information you asked:

The list of the remaining 152 proteins has been attached in here.

And I am also providing the proteins list which were in the 152 proteins and again aborted with the error code. 

Q92736
P21817
P56100
P98164
P43682
Q15413
P61039
Q9Y6D0
Q14571
Q86UQ4
P0ABA0
P36937
Q14643
P0DO45
Q9H5I5
P15484
Q8TDX9
P00856
P0AAW9

I will re-run the process for the 152 proteins with ray-trace 1°A enabled and cores set to 1 or 2.
[empty_folders.txt](https://github.com/uds-helms/ProPores2/files/10677800/empty_folders.txt)


All the protein files were extracted from Alphafold database of EMBL.

Best regards, 
Adnan

**Comment by mdka00001** [comment]
##Addition to the comment above##

I re-run the process on 151 proteins using `--mode 1` command and cores set to `2`. This time the process ended within few hours. So, it was very faster this time. However, the 20 proteins listed above did not generate any output for pore-id and axis-trace-input. I tried to re-run the process again on those remaining 20 proteins. Same results came through.

**Comment by Markus-Hollander** [comment]
Hello, 

I'm glad to hear that most of the remaining 150 proteins now worked in ray-trace mode. 

Unfortunately, when I search with the accessions above in Alphafold, it returns no search results. 

Could you please
1. attach a ZIP archive with the PDB files of the remaining 20 proteins? That way, I can have a look at them myself.
2. run `propores_status.py` on all your batches (so the 3500, the 150, the 20)? This is important because it will gather important statistics about structure sizes, runtime etc. which will make it a lot easier to figure when and why ProPores is struggling.

Kind regards,
Markus

**Comment by mdka00001** [comment]
Dear Markus,
Sorry for my late response.

To get rid of the ambiguity regarding the outputs, I re-run the entire process for 3453 proteins with ray-trace set to 1 and with axis-trace enabled and core set to 2. Propores successfully processed 3426 proteins and generated outputs for both pore-id and axis-trace. Only 27 proteins did not generate any pore id or axis-trace output. Some of the Alphafold IDs doesnot have any protein structure (we retreived the accession IDs from uniprot dataset). Others probably did not process due to large amino acid sequences. Here is the list of all the proteins:
P0AAW9
P0ABA0
*P0DO44
*P0DO45
*P15484
P21817
P33448
P36937
P43682
P56100
P56775
P56776
P61039
P62095
*P98164
P00856
*Q15413
Q5JRA6
*Q14571
*Q14643
Q8N4H5
Q8TDX9
*Q86UQ4
*Q92736
*Q9H5I5
Q9BV40
Q9Y6D0

'*' annotated proteins do not have any Alphafold structure.
However, I am having some difficulty running the 'propores_status.py' on my batch directory. I am getting an error "NoneType not iterable". Could you please instruct on this?

Regards,
Md Adnan Karim

**Comment by Markus-Hollander** [comment]
Dear Adnan,

Regarding the remaining proteins, I tried it with `P0AAW9` and downloaded the corresponding `AF-P0AAW9-F1-model_v4.pdb` from Alphafold. The run completes successfully and almost immediately. The reason, that there are no pores or axes in the results folder is simply that the structure is very small, consisting of only 372 atoms arranged in a single helix with a loop at the end, which simply does not have any possibility for pores, as can be seen in the 3D view on Alphafold:

![image](https://user-images.githubusercontent.com/7683033/220347780-e810a64e-ea20-4263-887a-b44c892b45bc.png)

The same is true for the next protein on the list (`P0ABA0`), so it should be worthwhile to quickly look at the Alphafold page of the other problem-causing structures, where you can see that at a glance.

Regarding `propores_status.py`, I could not reproduce the error. Here is an example of how I used it with the batch folder structure being the same as in the screenshots provided in a previous reply:

![image](https://user-images.githubusercontent.com/7683033/220347054-1616c402-91c0-4934-bdc3-00144a06552c.png)

(Note that on Ubuntu you would use `python3` instead of `python`.)

Did you call `propores_status.py` in the same way?

Kind regards,
Markus

**Comment by mdka00001** [comment]
Dear Markus,
Thanks a lot for the headsup. I believe I should have looked into the structures of the protein that didnot generate any output. After your explanation, It is clear to me. I will look for the other proteins as well.

Regarding ´propores_status.py´, I did the same way as your screenshot. For input i provided the directory of the folder containing all 3453 protein outputs. and for output i used a .txt file. but it doesnot generate any output. If I specify a specific protein, only then it gives me an output for the specific protein

**Comment by Markus-Hollander** [comment]
Could you perhaps share screenshots of the command and the directory structure of your input and output batch directories, similar to the ones I shared?

**Comment by mdka00001** [comment]
Hello Markus. Sorry for my delay in response. Here is how I run the command in my Ubuntu system.
![image](https://user-images.githubusercontent.com/65688206/234543972-012c1519-d191-4855-bfb7-e6acb47bfb78.png)

Here are the folders in the output directory:
![image](https://user-images.githubusercontent.com/65688206/234544255-c4f11d4f-e5ef-417c-8ed1-548627c60842.png)

**Comment by Markus-Hollander** [comment]
Hey,

it seems that for some reason, there is some issue with the generated log files for axis trace in one or more of your runs. You should be able to avoid the error if you replace the line
`if key in dictionary:`
with 
`if dictionary and key in dictionary:`
in line 10 of `propores_status.py` in the function `get_value`
Let me know if that resolves that error.
